source "https://api.berkshelf.com"

cookbook 'build-essential'
cookbook 'git'
cookbook 'memcached'
cookbook 'nodejs'
cookbook 'database'
cookbook 'xml'
cookbook 'ruby_build'
cookbook 'rbenv', :git => 'https://github.com/fnichol/chef-rbenv', :ref => 'v0.7.2'
cookbook 'nginx'
cookbook 'imagemagick'
cookbook 'simple_iptables', git:"git://github.com/dcrosta/cookbook-simple-iptables.git"
